version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /usr/node_modules
      - .:/usr
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/node_modules
      - .:/usr
    command: ["npm", "run", "test"]
    